# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BMFUser' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BMFUser
  pod 'Firebase/Core'
  # platform :ios, '9.0'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  target 'BMFUser-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BMFUserTests' do
    inherit! :search_paths
    # Pods for testing
  end

end